/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.gavin.ui;

import cn.gavin.action.TransferToSqlite;

import javax.crypto.NoSuchPaddingException;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;

/**
 * @author luoyuan
 */
public class Register extends javax.swing.JFrame {

/**
 * Creates new form Register
 */
public Register() {
	initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

	jLabel3 = new javax.swing.JLabel();
	key = new javax.swing.JTextField();
	jLabel1 = new javax.swing.JLabel();
	registButton = new javax.swing.JButton();
	jLabel2 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jMenuBar1 = new javax.swing.JMenuBar();
	jMenu1 = new javax.swing.JMenu();
	optionButton = new javax.swing.JMenuItem();
	quitButton = new javax.swing.JMenuItem();

	jLabel3.setText("jLabel3");

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	setTitle("注册用户");

	key.setHorizontalAlignment(javax.swing.JTextField.CENTER);
	key.setText("123dff-1dddd23-1ddd23-12ddd3-123");

	jLabel1.setText("输入用户的标识码");

	registButton.setText("注册");
	registButton.addActionListener(new ActionListener() {
		@Override public void actionPerformed(ActionEvent evt) {
			registButtonActionPerformed(evt);
		}
	});

	jLabel2.setText("点击注册后将会根据用户的标识码");
	jLabel2.setEnabled(false);

	jLabel4.setText(" 生成只有对应的用户才可以读取的数据文件");
	jLabel4.setEnabled(false);

	jMenu1.setText("File");

	optionButton.setText("设置");
	optionButton.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			optionButtonActionPerformed(evt);
		}
	});
	jMenu1.add(optionButton);

	quitButton.setText("退出");
	jMenu1.add(quitButton);

	jMenuBar1.add(jMenu1);

	setJMenuBar(jMenuBar1);

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(jLabel4)
									.addGroup(layout.createSequentialGroup()
											.addGap(91, 91, 91)
											.addComponent(registButton))
									.addGroup(layout.createSequentialGroup()
											.addGap(73, 73, 73)
											.addComponent(jLabel1))
									.addGroup(layout.createSequentialGroup()
											.addGap(28, 28, 28)
											.addComponent(jLabel2)))
							.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addComponent(key)
	);
	layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
							.addGap(6, 6, 6)
							.addComponent(jLabel1)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE,
									javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
							.addComponent(registButton)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
							.addComponent(jLabel2)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jLabel4)
							.addContainerGap(20, Short.MAX_VALUE))
	);

	pack();
}// </editor-fold>//GEN-END:initComponents

private void registButtonActionPerformed(ActionEvent evt) {
	TransferToSqlite transfer = new TransferToSqlite("", key.getText(), "", "");
	try {
		transfer.open();
		int page = transfer.getTotalPage();
		JProgressBar progressBar = new JProgressBar(0, page);
		JDialog dialog = new JDialog(this);
		dialog.add(progressBar);
		dialog.setAlwaysOnTop(true);
		progressBar.setValue(0);
		progressBar.setVisible(true);
		progressBar.setString("正在生成用户数据");
		dialog.setVisible(true);
		dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		for (int i = 1; i <= page; i++) {
			if (transfer.transfer(i)) {
				progressBar.setValue(i);
			} else {
				i--;
			}
		}
	} catch (ClassNotFoundException e) {
		e.printStackTrace();
	} catch (NoSuchPaddingException e) {
		e.printStackTrace();
	} catch (NoSuchAlgorithmException e) {
		e.printStackTrace();
	} catch (InvalidKeyException e) {
		e.printStackTrace();
	} catch (SQLException e) {
		e.printStackTrace();
	}

}

private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionButtonActionPerformed
	JDialog dialog = new JDialog(this);
	dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	dialog.add(new OptionView());
	dialog.setTitle("设置");
	dialog.setVisible(true);
}//GEN-LAST:event_optionButtonActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
		/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
	try {
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				javax.swing.UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	} catch (ClassNotFoundException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
		java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

        /* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
		public void run() {
			new Register().setVisible(true);
		}
	});
}

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JMenu jMenu1;
private javax.swing.JMenuBar jMenuBar1;
private javax.swing.JTextField key;
private javax.swing.JMenuItem optionButton;
private javax.swing.JMenuItem quitButton;
private javax.swing.JButton registButton;
// End of variables declaration//GEN-END:variables
}
